# Generated by Django 4.1.1 on 2022-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_billingrecord_hosts"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.CharField(max_length=1024)),
                ("plan_id", models.CharField(max_length=1024)),
                ("base_quantity", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="billedhost",
            name="reported",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="basequantity",
            constraint=models.UniqueConstraint(
                fields=("offer_id", "plan_id"), name="Unique offer plan pairs"
            ),
        ),
    ]
