# Generated by Django 3.2.22 on 2024-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_basequantity_billedhost_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='azure_dimension',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_effective_start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_message_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_plan_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_resource_id',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='azure_status',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
