# Generated by Django 5.0.6 on 2024-05-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_billingrecord_add_azure"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingrecord",
            name="azure_resource_uri",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="billingrecord",
            name="resource_uri",
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="billingrecord",
            name="resource_id",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
