# Generated by Django 3.2.9 on 2022-02-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BilledHost',
            fields=[
                ('billed_date', models.DateTimeField()),
                ('host_name', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('rollover_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'billed hosts',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billed_date', models.DateTimeField()),
                ('dimension', models.CharField(max_length=1024)),
                ('quantity', models.IntegerField()),
                ('hosts', models.CharField(max_length=1024)),
                ('managed_app_id', models.CharField(max_length=1024)),
                ('resource_id', models.CharField(max_length=1024)),
                ('plan', models.CharField(max_length=1024)),
                ('usage_event_id', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'billing records',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='InstallDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('install_date', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='RolloverDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollover_date', models.DateTimeField(default=None)),
            ],
        ),
    ]
