# Generated by Django 3.2.10 on 2021-12-14 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BilledHost",
            fields=[
                ("billed_date", models.DateTimeField()),
                (
                    "host_name",
                    models.CharField(
                        max_length=1024, primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "billed hosts",
                "ordering": ("-pk",),
            },
        ),
        migrations.CreateModel(
            name="BillingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billed_date", models.DateTimeField()),
                ("dimension", models.CharField(max_length=1024)),
                ("quantity", models.IntegerField()),
                ("hosts", models.CharField(max_length=1024)),
                ("managed_app_id", models.CharField(max_length=1024)),
                ("resource_id", models.CharField(max_length=1024)),
                ("plan", models.CharField(max_length=1024)),
                ("usage_event_id", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name_plural": "billing records",
                "ordering": ("-pk",),
            },
        ),
    ]
